#!/usr/bin/env node
// Generate THIRD-PARTY-NOTICES.md (#222): the attribution + license texts for
// every third-party dependency Cartograph ships — Rust crates (via cargo-about)
// and the production npm packages in ui/.
//
// Output is DETERMINISTIC (no timestamps, sorted) so CI can regenerate and diff
// it against the committed copy to catch drift. Also emits a code-split TS
// module the app imports for its in-app "Open-source licenses" view.
//
// Usage:  node scripts/generate-notices.mjs [--check]
//   (no flag)  write the files
//   --check    regenerate in memory and fail if the committed files are stale
//
// Requires: cargo-about on PATH, and `npm ci` already run in ui/.

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const NOTICES_PATH = join(ROOT, 'THIRD-PARTY-NOTICES.md');
const TS_PATH = join(ROOT, 'ui', 'src', 'generated', 'thirdPartyNotices.ts');
const check = process.argv.includes('--check');

function run(cmd, args, cwd) {
  return execFileSync(cmd, args, {
    cwd,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'inherit'],
  });
}

// --- Rust: cargo-about renders about.hbs against the locked crate graph. ---
// `--offline --locked` keeps output reproducible (no clearlydefined.io / lock
// drift) so the CI drift-check is stable. cargo-deny is the license *gate*;
// this step only renders notices, so our own (PolyForm-licensed) workspace
// crates are simply skipped by cargo-about with a warning rather than failing.
function rustNotices() {
  const out = run('cargo', ['about', 'generate', 'about.hbs', '--offline', '--locked'], ROOT);
  return out.trimEnd();
}

// --- JavaScript: walk the production dependency tree that ui/ actually ships. ---
function collectJsPackages() {
  const uiDir = join(ROOT, 'ui');
  const raw = run('npm', ['ls', '--omit=dev', '--all', '--json'], uiDir);
  const tree = JSON.parse(raw);
  const found = new Map(); // name@version -> {name, version}
  const walk = (deps) => {
    for (const [name, info] of Object.entries(deps ?? {})) {
      if (!info || info.version == null) continue;
      const key = `${name}@${info.version}`;
      if (!found.has(key)) found.set(key, { name, version: info.version });
      walk(info.dependencies);
    }
  };
  walk(tree.dependencies);
  return [...found.values()].sort((a, b) =>
    a.name === b.name ? a.version.localeCompare(b.version) : a.name.localeCompare(b.name),
  );
}

function readJsLicense(pkg) {
  // node_modules is hoisted, so the package almost always sits at the top level.
  const dir = join(ROOT, 'ui', 'node_modules', pkg.name);
  let spdx = 'See package';
  let text = '';
  const manifestPath = join(dir, 'package.json');
  if (existsSync(manifestPath)) {
    try {
      const m = JSON.parse(readFileSync(manifestPath, 'utf8'));
      if (typeof m.license === 'string') spdx = m.license;
      else if (m.license?.type) spdx = m.license.type;
      else if (Array.isArray(m.licenses)) spdx = m.licenses.map((l) => l.type).join(' OR ');
    } catch {
      /* keep default */
    }
    try {
      const file = readdirSync(dir).find((f) => /^(LICEN[CS]E|COPYING)/i.test(f));
      if (file) text = readFileSync(join(dir, file), 'utf8').trimEnd();
    } catch {
      /* no license file bundled */
    }
  }
  return { spdx, text };
}

function jsNotices() {
  const pkgs = collectJsPackages();
  const lines = [
    'Cartograph bundles the following npm packages in its web UI. Each is used',
    'under the terms of its declared license. This list is generated from the',
    'production dependency tree by `npm ls`; do not edit by hand.',
    '',
  ];
  for (const pkg of pkgs) {
    const { spdx, text } = readJsLicense(pkg);
    lines.push(`## ${pkg.name} ${pkg.version}`, '', `License: ${spdx}`, '');
    if (text) lines.push('```', text, '```', '');
  }
  return lines.join('\n').trimEnd();
}

function build() {
  const body = [
    '# Third-Party Notices',
    '',
    'Cartograph itself is licensed under the PolyForm Noncommercial License 1.0.0',
    '(see `LICENSE.md`). It also incorporates third-party open-source software,',
    'each under its own license, reproduced in full below.',
    '',
    'This file is generated — run `node scripts/generate-notices.mjs` to refresh',
    'it. CI fails if it drifts from the dependency manifests.',
    '',
    '---',
    '',
    '# Rust crates',
    '',
    rustNotices(),
    '',
    '---',
    '',
    '# npm packages (web UI)',
    '',
    jsNotices(),
    '',
  ].join('\n');
  return body;
}

function tsModule(markdown) {
  return (
    '// GENERATED by scripts/generate-notices.mjs — do not edit.\n' +
    '// Full third-party attribution for the in-app "Open-source licenses" view.\n' +
    `export const THIRD_PARTY_NOTICES = ${JSON.stringify(markdown)};\n`
  );
}

const notices = build();
const ts = tsModule(notices);

if (check) {
  const staleNotices = !existsSync(NOTICES_PATH) || readFileSync(NOTICES_PATH, 'utf8') !== notices;
  const staleTs = !existsSync(TS_PATH) || readFileSync(TS_PATH, 'utf8') !== ts;
  if (staleNotices || staleTs) {
    console.error(
      'THIRD-PARTY-NOTICES is out of date. Run `node scripts/generate-notices.mjs` and commit the result.',
    );
    process.exit(1);
  }
  console.log('Third-party notices are up to date.');
} else {
  writeFileSync(NOTICES_PATH, notices);
  writeFileSync(TS_PATH, ts);
  console.log(`Wrote ${NOTICES_PATH} and ${TS_PATH}.`);
}
